<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <AssemblyName>til</AssemblyName>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ICSharpCode.Decompiler" Version="9.1.0.7988" />
      <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="4.0.0-beta.24463.1" />
      <PackageReference Include="Microsoft.Diagnostics.Runtime.Utilities" Version="4.0.0-beta.24463.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\\ObjectGraph\\ObjectGraph.csproj" />
    </ItemGroup>

</Project>
